"""Mutation testing for the UE bridge: every mutant must make its named test
fail. Run after a task's tests pass:

    python tools/mutate_ue_bridge.py [task] [--path FILE ...]

--path (repeatable, relative to the repository root) keeps only the mutants of
those files; with a task it is an AND. Use it to avoid rewriting files another
build is reading.

Mutants are single-line replacements (the checkout's line endings vary).
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

# run as a script, Python puts tools/ on the path, not the repository root
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from tools import ue_bridge_tests  # noqa: E402


@dataclass(frozen=True)
class Mutant:
    task: str
    path: str  # relative to the repository root
    original: str  # one line, occurring exactly once in the file
    mutated: str
    killed_by: str  # a test-name filter for ue_bridge_tests.exe, or "pytest:<test name>" for a cross-process test
    runs: int = 1  # for a mutant a timing-dependent test kills only some of the time: killed if any run fails


MUTANTS = [
    Mutant("1", "port/ue_bridge/ue_bridge_ring.c",
           "if (ueb_load_u32(&slot->sequence) != before)", "if (0)",
           "slot_try_read_detects_change_during_copy"),
    Mutant("1", "port/ue_bridge/ue_bridge_ring.c",
           "if (before & 1u)", "if (0)",
           "ring_read_takes_previous_while_newest_is_odd"),
    Mutant("1", "port/ue_bridge/ue_bridge_ring.c",
           "<= section_size;", "<= section_size + slot_size;",
           "ring_valid_rejects_a_ring_past_the_section"),
    Mutant("1", "port/ue_bridge/ue_bridge_ring.c",
           "ueb_store_u32(&ring->published, ring->published + 1u);", ";",
           "ring_write_then_read_newest"),
    Mutant("1", "port/ue_bridge/ue_bridge_ring.c",
           "if (slot_count < 2u", "if (slot_count < 1u",
           "ring_valid_rejects_fewer_than_two_slots"),
    # a 64-bit store split into two 32-bit halves: the torn-store stress test must see it
    Mutant("1", "port/ue_bridge/ue_bridge_ring.h",
           "__atomic_store_n(address, value, __ATOMIC_SEQ_CST);",
           "((volatile uint32_t *)address)[0] = (uint32_t)value; ((volatile uint32_t *)address)[1] = (uint32_t)(value >> 32);",
           "ring_heartbeat_store_is_never_torn"),
    Mutant("2", "port/ue_bridge/ue_bridge_policy.c",
           "if (peer->stopping == UE_BRIDGE_STOP_CRASH || ue_bridge_exit_code_is_crash(peer->exit_code))",
           "if (ue_bridge_exit_code_is_crash(peer->exit_code))",
           "policy_published_crash_is_crashed_whatever_the_exit_code"),
    Mutant("2", "port/ue_bridge/ue_bridge_policy.c",
           "return exit_code >= 0xC0000000u;", "return exit_code > 0xC0000000u;",
           "policy_exit_code_classification"),
    Mutant("2", "port/ue_bridge/ue_bridge_policy.c",
           "if (peer->debugger_attached || peer->busy || peer->heartbeat_qpc == 0 || qpc_frequency == 0)",
           "if (peer->busy || peer->heartbeat_qpc == 0 || qpc_frequency == 0)",
           "policy_debugger_suppresses_hang"),
    Mutant("2", "port/ue_bridge/ue_bridge_policy.c",
           "if (peer->debugger_attached || peer->busy || peer->heartbeat_qpc == 0 || qpc_frequency == 0)",
           "if (peer->debugger_attached || peer->heartbeat_qpc == 0 || qpc_frequency == 0)",
           "policy_busy_suppresses_hang"),
    Mutant("2", "port/ue_bridge/ue_bridge_policy.c",
           "if (now_qpc <= peer->heartbeat_qpc)", "if (0)",
           "policy_heartbeat_ahead_of_now_is_not_a_hang"),
    Mutant("2", "port/ue_bridge/ue_bridge_policy.c",
           "timeout_ms = peer->hang_timeout_ms ? peer->hang_timeout_ms : UE_BRIDGE_DEFAULT_HANG_TIMEOUT_MS;",
           "timeout_ms = UE_BRIDGE_DEFAULT_HANG_TIMEOUT_MS;",
           "policy_stall_below_peer_timeout_is_not_a_hang"),
    Mutant("2", "port/ue_bridge/ue_bridge_policy.c",
           "if (age_ms <= timeout_ms)", "if (age_ms < timeout_ms)",
           "policy_stall_below_peer_timeout_is_not_a_hang"),
    Mutant("2", "port/ue_bridge/ue_bridge_policy.c",
           "return peer->is_editor ? UE_BRIDGE_ACTION_PEER_HUNG_EDITOR : UE_BRIDGE_ACTION_PEER_HUNG;",
           "return UE_BRIDGE_ACTION_PEER_HUNG;",
           "policy_editor_hang_is_hung_editor"),
    Mutant("2", "port/ue_bridge/ue_bridge_policy.c",
           "if (ue_bridge_peer_winding_down(peer))", "if (0)",
           "policy_crashing_peer_is_crashing"),
    Mutant("2", "port/ue_bridge/ue_bridge_policy.c",
           "if (peer->crashing_for_ms > UE_BRIDGE_CRASHING_LIMIT_MS && !peer->debugger_attached)", "if (!peer->debugger_attached)",
           "policy_crashing_too_long_is_hung"),
    Mutant("2", "port/ue_bridge/ue_bridge_policy.c",
           "return !continue_on_peer_exit;", "return 1;",
           "policy_shutdown_follows_continue_mode"),
    Mutant("2", "port/ue_bridge/ue_bridge_policy.c",
           "if (peer->crashing_for_ms > UE_BRIDGE_CRASHING_LIMIT_MS && !peer->debugger_attached)",
           "if (peer->crashing_for_ms > UE_BRIDGE_CRASHING_LIMIT_MS)",
           "policy_debugger_suppresses_crashing_too_long"),
    Mutant("11", "port/ue_bridge/ue_bridge_policy.c",
           "return peer->crashing != 0 || peer->stopping != UE_BRIDGE_STOP_NONE;", "return peer->crashing != 0;",
           "policy_winding_down_is_crashing_or_stopping"),
    Mutant("11", "port/ue_bridge/ue_bridge_policy.c",
           "return peer->crashing != 0 || peer->stopping != UE_BRIDGE_STOP_NONE;", "return peer->crashing != 0 || peer->stopping == UE_BRIDGE_STOP_CRASH;",
           "policy_exiting_live_peer_is_left_alone_within_the_limit"),
    Mutant("11", "port/ue_bridge/ue_bridge_policy.c",
           "if (peer->crashing_for_ms > UE_BRIDGE_CRASHING_LIMIT_MS && !peer->debugger_attached)",
           "if (peer->crashing_for_ms > UE_BRIDGE_CRASHING_LIMIT_MS * 2u && !peer->debugger_attached)",
           "policy_exiting_live_peer_past_the_limit_is_hung"),
    Mutant("11", "port/ue_bridge/ue_bridge_policy.c",
           "return peer->crashing || peer->stopping == UE_BRIDGE_STOP_CRASH ? UE_BRIDGE_ACTION_PEER_CRASHING : UE_BRIDGE_ACTION_NONE;",
           "return UE_BRIDGE_ACTION_PEER_CRASHING;",
           "policy_exiting_live_peer_is_left_alone_within_the_limit"),
    Mutant("11", "port/windows/src/win32_ue_bridge.c",
           "view.crashing_for_ms = ue_bridge_crashing_for_ms(&crash_clock, ue_bridge_peer_winding_down(&view), GetTickCount());",
           "view.crashing_for_ms = ue_bridge_crashing_for_ms(&crash_clock, view.crashing, GetTickCount());",
           "pytest:test_game_ends_an_exiting_ue_that_never_finishes_after_the_grace"),
    Mutant("11", "port/windows/src/win32_ue_bridge.c",
           "view.crashing_for_ms = ue_bridge_crashing_for_ms(&crash_clock, ue_bridge_peer_winding_down(&view), GetTickCount());",
           "view.crashing_for_ms = 0;",
           "pytest:test_game_ends_an_exiting_ue_that_never_finishes_after_the_grace"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "if (bridge.section_view || !settings->enabled)", "if (bridge.section_view)",
           "core_disabled_maps_nothing"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "if (!bridge.session_id)", "if (0)",
           "core_zero_random_session_becomes_one"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "uint32_t odd = ueb_load_u32(&directory->sequence) | 1u;",
           "uint32_t odd = ueb_load_u32(&directory->sequence) + 1u;",
           "core_directory_left_odd_by_dead_game_is_repaired"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "if (directory->session_id == bridge.session_id)", "if (1)",
           "core_stop_keeps_a_newer_games_directory_entry"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "if (source && strlen(source) < capacity)", "if (source && strlen(source) <= capacity)",
           "core_log_path_that_does_not_fit_is_published_empty"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "if (source && strlen(source) < capacity)", "if (source && strlen(source) + 1 < capacity)",
           "core_log_path_that_just_fits_is_published_whole"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "utf8[0] = 0;", ";",
           "core_log_path_from_a_silently_failing_conversion_is_empty"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "bridge.os->debugger_present() ? 1u : 0u", "0u",
           "core_heartbeat_tracks_qpc_and_debugger"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "bridge.tick_slot->id = tick;", "bridge.tick_slot->id = 0;",
           "core_publish_tick_and_frame"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "ueb_store_u32(&header->game_busy, busy ? 1u : 0u);", ";",
           "core_busy_flag_round_trips"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "os->unmap_section(bridge.section_view, bridge.section_handle);", ";",
           "core_directory_failure_unmaps_section"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "ueb_store_u32(&header->game_stopping, stopping);", ";",
           "core_stop_clears_own_directory_entry_and_unmaps"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "header->magic = UE_BRIDGE_MAGIC;",
           "{ void *v, *h; v = os->map_section(UE_BRIDGE_DIRECTORY_NAME, UE_BRIDGE_DIRECTORY_SIZE, &h); publish_directory((volatile struct ue_bridge_directory *)v, pid, section_name); } header->magic = UE_BRIDGE_MAGIC;",
           "core_header_is_complete_when_the_directory_is_mapped"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "uint32_t sequence = directory_begin_write(directory);",
           "uint32_t sequence = ueb_load_u32(&directory->sequence) - 1u;",
           "core_directory_writes_begin_with_the_sequence"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "uint32_t odd = directory_begin_write(directory);",
           "directory->session_id = bridge.session_id; uint32_t odd = directory_begin_write(directory);",
           "core_directory_writes_begin_with_the_sequence"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "ue_bridge_publish_stopping(stopping);",
           "bridge.os->unmap_section(section_view, bridge.section_handle); bridge.os->unmap_section(bridge.directory_view, bridge.directory_handle); ue_bridge_publish_stopping(stopping);",
           "core_stop_writes_before_it_unmaps"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "ue_bridge_ring_end_write(&header->tick_ring, bridge.tick_slot);",
           "bridge.tick_slot->publish_qpc = 0; ue_bridge_ring_end_write(&header->tick_ring, bridge.tick_slot); bridge.tick_slot->publish_qpc = bridge.os->qpc();",
           "core_concurrent_reader_never_sees_a_tick_without_its_payload"),
    Mutant("3", "port/linux/src/ue_bridge.c",
           "bridge.os->unlock_directory();", ";",
           "core_start_and_stop_each_take_the_directory_lock_once"),
    Mutant("4", "port/linux/src/ue_bridge_game.c",
           "if (!config_boolean(\"ue_bridge.enabled\"))", "if (0)",
           "game_disabled_starts_nothing"),
    Mutant("4", "port/linux/src/ue_bridge_game.c",
           "watch.continue_on_peer_exit = strcmp(on_peer_exit, \"continue\") == 0;",
           "watch.continue_on_peer_exit = 0;",
           "game_continue_setting_reaches_watcher"),
    Mutant("4", "port/linux/src/ue_bridge_game.c",
           "if (!ue_bridge_platform_start_watcher(&watch))",
           "if (!ue_bridge_platform_start_watcher(&watch) && 0)",
           "game_watcher_failure_stops_bridge"),
    Mutant("4", "port/linux/src/ue_bridge_game.c",
           "if (start_attempted)", "if (start_attempted && 0)",
           "game_starts_only_once"),
    Mutant("4", "port/linux/src/ue_bridge_game.c",
           "ue_bridge_platform_stop_watcher();", ";",
           "game_shutdown_stops_watcher_and_bridge"),
    Mutant("4", "port/linux/src/ue_bridge_game.c",
           "ue_bridge_set_busy(loading);", ";",
           "game_loading_sets_and_clears_busy"),
    Mutant("4", "port/linux/src/ue_bridge_game.c",
           "ue_bridge_publish_stopping(UE_BRIDGE_STOP_CRASH);", ";",
           "game_halted_stops_heartbeat_and_publishes_crash"),
    Mutant("4", "port/linux/src/ue_bridge_game.c",
           "if (started && !halted)", "if (started)",
           "game_halted_stops_heartbeat_and_publishes_crash"),
    Mutant("4", "port/linux/src/ue_bridge_game.c",
           "if (!halted)", "if (1)",
           "game_halted_stops_heartbeat_and_publishes_crash"),
    Mutant("4", "port/linux/src/ue_bridge_game.c",
           "ue_bridge_set_busy(0);", ";",
           "game_halted_stops_heartbeat_and_publishes_crash"),
    Mutant("4", "port/linux/src/ue_bridge_game.c",
           "halted = 0;", ";",
           "game_shutdown_after_halt_beats_again_on_restart"),
    Mutant("4", "port/linux/src/ue_bridge_game.c",
           "int stopping = halted ? UE_BRIDGE_STOP_CRASH : UE_BRIDGE_STOP_EXIT;",
           "int stopping = UE_BRIDGE_STOP_EXIT;",
           "game_shutdown_after_halt_keeps_the_published_crash"),
    Mutant("4", "port/linux/src/ue_bridge.c",
           "ueb_store_u32(&header->game_stopping, stopping);", "(void)stopping;",
           "core_publish_stopping_sets_flag_only_when_active"),
    Mutant("5", "port/linux/src/ue_bridge.c",
           "__atomic_store_n(&bridge.section_view, NULL, __ATOMIC_SEQ_CST);", ";",
           "core_stop_hides_the_header_from_the_crash_filter_before_unmapping_it"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "if (action == UE_BRIDGE_ACTION_PEER_HUNG)", "if (0)",
           "pytest:test_game_kills_hung_standalone_ue"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "if (ue_bridge_policy_shuts_down(action, watch_config.continue_on_peer_exit))", "if (1)",
           "pytest:test_continue_mode_keeps_game_running"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "GetTickCount() - start < UE_BRIDGE_DUMP_WAIT_MS", "(GetTickCount() - start < UE_BRIDGE_DUMP_WAIT_MS || 1)",
           "pytest:test_crash_wait_is_capped_when_ue_ignores_it"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "previous_filter = SetUnhandledExceptionFilter(bridge_crash_filter);", "(void)bridge_crash_filter;",
           "pytest:test_crash_self_dumps_when_no_ue"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "write_self_dump(dump_exception, dump_header, dump_crashing_thread);", ";",
           "pytest:test_crash_self_dumps_when_no_ue"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "view->debugger_attached = ueb_load_u32(&header->ue_debugger_attached) != 0;", "view->debugger_attached = 0;",
           "pytest:test_no_hang_action_while_ue_debugger_flag_set"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "view->is_editor = ueb_load_u32(&header->ue_is_editor) != 0;", "view->is_editor = 0;",
           "pytest:test_game_never_kills_hung_editor_ue"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "view->hang_timeout_ms = ueb_load_u32(&header->ue_hang_timeout_ms);", "view->hang_timeout_ms = 0;",
           "pytest:test_game_kills_hung_standalone_ue"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "view->stopping = ueb_load_u32(&header->ue_stopping);", "view->stopping = 0;",
           "pytest:test_game_leaves_a_crashing_ue_alone"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "view->busy = ueb_load_u32(&header->ue_busy) != 0;", "view->busy = 0;",
           "pytest:test_no_hang_action_while_ue_busy"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "write_header_snapshot(directory, header);", "(void)write_header_snapshot;",
           "pytest:test_game_report_carries_the_header_and_ues_crash_folder"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "result = WaitForSingleObject(directory_mutex, DIRECTORY_LOCK_WAIT_MS);", "result = WAIT_TIMEOUT;",
           "pytest:test_two_games_are_never_inside_the_directory_lock_together"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "result = WaitForSingleObject(directory_mutex, DIRECTORY_LOCK_WAIT_MS);", "result = WaitForSingleObject(directory_mutex, INFINITE);",
           "pytest:test_a_hung_directory_lock_holder_delays_game_start_by_the_cap_only"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "if (result == WAIT_OBJECT_0 || result == WAIT_ABANDONED)", "if (result == WAIT_OBJECT_0)",
           "pytest:test_an_abandoned_directory_lock_is_taken_over_without_waiting"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "DWORD length = GetFullPathNameA(path, sizeof(full), full, NULL);", "DWORD length = (strcpy(full, path), (DWORD)strlen(path));",
           "pytest:test_published_log_path_is_made_absolute"),
    Mutant("5", "port/ue_bridge/ue_bridge_policy.c",
           "return now_ms - clock->since_ms;", "return now_ms > clock->since_ms ? now_ms - clock->since_ms : 0;",
           "policy_crash_clock_is_wrap_safe"),
    Mutant("5", "port/ue_bridge/ue_bridge_policy.c",
           "clock->since_ms = now_ms;", "clock->since_ms = now_ms | 1u;",
           "policy_crash_clock_first_sighting_at_an_even_time_is_zero"),
    Mutant("5", "port/ue_bridge/ue_bridge_policy.c",
           "clock->active = 0;", ";",
           "policy_crash_clock_resets_when_crashing_stops"),
    Mutant("5", "port/ue_bridge/ue_bridge_policy.c",
           "clock->active = 1;", ";",
           "policy_crash_clock_elapsed_time_grows"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "result = previous_filter ? previous_filter(exception) : EXCEPTION_CONTINUE_SEARCH;", "result = EXCEPTION_CONTINUE_SEARCH; (void)previous_filter;",
           "pytest:test_crash_self_dumps_when_no_ue"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "TerminateProcess(GetCurrentProcess(), code);", ";",
           "pytest:test_crash_self_dumps_when_no_ue"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "InterlockedExchange(&crash_owner, 0);", ";",
           "pytest:test_a_crash_hook_that_outlived_the_bridge_does_not_park_a_later_crash"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "SetThreadStackGuarantee(&guarantee);", "dump_thread = NULL; (void)guarantee;",
           "pytest:test_stack_overflow_still_writes_the_self_dump"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "result = WaitForSingleObject(directory_mutex, DIRECTORY_LOCK_WAIT_MS);", "return;",
           "pytest:test_two_games_are_never_inside_the_directory_lock_together"),
    Mutant("5", "port/windows/src/win32_ue_bridge.c",
           "ReleaseMutex(directory_mutex);", ";",
           "pytest:test_a_second_game_starts_without_waiting_for_a_live_first_game"),
    Mutant("10", "port/ue_bridge/tests/roles.c",
           "if (file_exists(exit_when))", "if (file_exists(exit_when) && 0)",
           "pytest:test_exit_when_file_appears"),
    Mutant("10", "port/ue_bridge/tests/roles.c",
           "hanging = 1;", "{ hanging = 1; ue_bridge_publish_frame(++frame, 0.5f); }",
           "pytest:test_hang_when_file_appears"),
    Mutant("10", "port/ue_bridge/tests/roles.c",
           'ended = "exit file";', 'ended = "run time over";',
           "pytest:test_exit_when_file_appears"),
    Mutant("10", "port/ue_bridge/tests/roles.c",
           "if ((crash_after >= 0 && elapsed >= crash_after) || file_exists(crash_when))",
           "if ((crash_after >= 0 && elapsed >= crash_after) || (file_exists(crash_when) && 0))",
           "pytest:test_crash_when_file_appears"),
    Mutant("10", "port/ue_bridge/tests/roles.c",
           "if (!hanging && (hang_after < 0 || elapsed < hang_after))", "if ((hanging || 1) && (hang_after < 0 || elapsed < hang_after))",
           "pytest:test_hang_when_file_appears"),
    Mutant("14", "port/linux/src/ue_bridge_log.c",
           "write_to_error_file(line, 1);", ";",
           "game_log_lines_reach_the_debug_file"),
    Mutant("14", "port/linux/src/ue_bridge_log.c",
           "write_to_error_file(line, 1);", "write_to_error_file(line, 0);",
           "game_log_lines_reach_the_debug_file"),
    Mutant("14", "port/linux/src/ue_bridge_log.c",
           'platform_log("%s", line);', ";",
           "game_log_lines_reach_the_debug_file"),
    Mutant("14", "port/linux/src/ue_bridge_log.c",
           "line[length] = '\\r';", "line[length] = ' ';",
           "game_log_lines_reach_the_debug_file"),
    Mutant("14", "port/windows/src/win32_ue_bridge.c",
           'ue_bridge_log("ue bridge: renderer %lu attached", (unsigned long)pid);',
           'printf("ue bridge: renderer %lu attached\\n", (unsigned long)pid);',
           "pytest:test_the_games_bridge_messages_reach_its_debug_file"),
    Mutant("14", "port/linux/src/ue_bridge_game.c",
           'ue_bridge_log("ue bridge: on, session %016llx", (unsigned long long)ue_bridge_session_id());',
           'printf("ue bridge: on, session %016llx\\n", (unsigned long long)ue_bridge_session_id());',
           "game_log_lines_reach_the_debug_file"),
    Mutant("15", 'port/ue_bridge/ue_bridge_frame_rate.h',
           'if (vsync || max_fps < 0)',
           'if (max_fps < 0)',
           'frame_rate_limit_is_none_with_vsync_or_a_negative_maximum'),
    Mutant("15", 'port/ue_bridge/ue_bridge_frame_rate.h',
           'if (vsync || max_fps < 0)',
           'if (vsync)',
           'frame_rate_limit_is_none_with_vsync_or_a_negative_maximum'),
    Mutant("15", 'port/ue_bridge/ue_bridge_frame_rate.h',
           'return 2.0f * ue_bridge_refresh_or_default(refresh_hz);',
           'return ue_bridge_refresh_or_default(refresh_hz);',
           'frame_rate_limit_zero_maximum_is_twice_the_refresh_rate'),
    Mutant("15", 'port/ue_bridge/ue_bridge_frame_rate.h',
           'return refresh_hz > 0.0f ? refresh_hz : UE_BRIDGE_DEFAULT_REFRESH_HZ;',
           'return refresh_hz;',
           'frame_rate_limit_unknown_refresh_rate_counts_as_60'),
    Mutant("15", 'port/ue_bridge/ue_bridge_frame_rate.h',
           'target = refresh_hz > 0.0f ? (uint32_t)(refresh_hz + 0.5f) : 0;',
           'target = refresh_hz > 0.0f ? (uint32_t)refresh_hz : 0;',
           'frame_rate_target_with_vsync_rounds_the_refresh_rate'),
    Mutant("15", 'port/ue_bridge/ue_bridge_frame_rate.h',
           'target = refresh_hz > 0.0f ? (uint32_t)(refresh_hz + 0.5f) : 0;',
           'target = (uint32_t)(ue_bridge_refresh_or_default(refresh_hz) + 0.5f);',
           'frame_rate_target_with_vsync_and_an_unknown_refresh_rate_is_uncapped'),
    Mutant("15", 'port/ue_bridge/ue_bridge_frame_rate.h',
           'if (!interpolation && (target == 0 || target > UE_BRIDGE_ORIGINAL_FRAME_RATE))',
           'if (!interpolation && target > UE_BRIDGE_ORIGINAL_FRAME_RATE)',
           'frame_rate_target_without_interpolation_is_the_original_30'),
    Mutant("15", 'port/ue_bridge/ue_bridge_frame_rate.h',
           'if (!interpolation && (target == 0 || target > UE_BRIDGE_ORIGINAL_FRAME_RATE))',
           'if (!interpolation && target == 0)',
           'frame_rate_target_without_interpolation_is_the_original_30'),
    Mutant("15", 'port/ue_bridge/ue_bridge_frame_rate.h',
           'if (!interpolation && (target == 0 || target > UE_BRIDGE_ORIGINAL_FRAME_RATE))',
           'if (0)',
           'frame_rate_target_without_interpolation_is_the_original_30'),
    Mutant("15", 'port/ue_bridge/ue_bridge_frame_rate.h',
           'target = refresh_hz > 0.0f ? (uint32_t)(refresh_hz + 0.5f) : 0;',
           'target = (uint32_t)(ue_bridge_frame_limit_rate(0, max_fps, refresh_hz) + 0.5f);',
           'frame_rate_target_with_vsync_is_the_refresh_rate'),
    Mutant("15", 'port/ue_bridge/ue_bridge_frame_rate.h',
           'target = (uint32_t)(ue_bridge_frame_limit_rate(0, max_fps, refresh_hz) + 0.5f);',
           'target = (uint32_t)max_fps;',
           'frame_rate_target_without_vsync_follows_the_maximum'),
    Mutant("15", 'port/linux/src/ue_bridge.c',
           'ueb_store_u32(&header->game_frame_target_hz, target_hz);',
           'ueb_store_u32(&header->game_frame_target_hz, refresh_hz);',
           'core_publish_frame_rate_writes_both_fields_and_republishes'),
    Mutant("15", 'port/linux/src/ue_bridge.c',
           'ueb_store_u32(&header->game_refresh_hz, refresh_hz);',
           ';',
           'core_publish_frame_rate_writes_both_fields_and_republishes'),
    Mutant("15", 'port/linux/src/ue_bridge.c',
           'ueb_store_u32(&header->game_refresh_hz, refresh_hz);',
           'ueb_store_u32(&header->game_refresh_hz, target_hz);',
           'pytest:test_the_game_publishes_its_refresh_rate_and_frame_target'),
    Mutant("15", 'port/linux/src/ue_bridge_game.c',
           'if (frame_rate_published && refresh_hz == published_refresh_hz && target_hz == published_target_hz)',
           'if (frame_rate_published && refresh_hz == published_refresh_hz && (target_hz == published_target_hz || refresh_hz != 0))',
           'game_frame_rate_poll_republishes_on_a_change'),
    Mutant("15", 'port/linux/src/ue_bridge_game.c',
           'if (frame_rate_published && refresh_hz == published_refresh_hz && target_hz == published_target_hz)',
           'if (frame_rate_published && target_hz == published_target_hz && (refresh_hz == published_refresh_hz || target_hz == 0))',
           'game_frame_rate_poll_republishes_on_a_change'),
    Mutant("15", 'port/linux/src/ue_bridge_game.c',
           'if (frame_rate_published && refresh_hz == published_refresh_hz && target_hz == published_target_hz)',
           'if (frame_rate_published && refresh_hz == published_refresh_hz && target_hz == published_target_hz && 0)',
           'game_frame_rate_poll_logs_only_a_change'),
    Mutant("15", 'port/linux/src/ue_bridge_game.c',
           '\tframe_rate_published = 0;',
           '\t;',
           'game_frame_rate_poll_after_a_restart_publishes_again'),
    Mutant("15", 'port/linux/src/ue_bridge_game.c',
           '\tue_bridge_game_frame_rate_poll();',
           '\t;',
           'game_start_publishes_the_frame_rate'),
    Mutant("15", 'port/linux/src/ue_bridge_game.c',
           'refresh_hz = (uint32_t)(refresh + 0.5f);',
           'refresh_hz = (uint32_t)refresh;',
           'game_start_publishes_the_frame_rate'),
    Mutant("15", 'port/linux/src/ue_bridge_game.c',
           'ue_bridge_log("ue bridge: frame rate uncapped, display %lu Hz", (unsigned long)refresh_hz);',
           'printf("ue bridge: frame rate uncapped, display %lu Hz\\n", (unsigned long)refresh_hz);',
           'game_frame_rate_poll_logs_only_a_change'),
    Mutant("m2a-2", "port/ue_bridge/ue_bridge_load.c",
           "if (load_offset + UE_BRIDGE_MIN_LOAD_SIZE > section_size)", "if (load_offset > section_size)",
           "layout_rejects_a_section_without_room_for_a_load_region"),
    Mutant("m2a-2", "port/ue_bridge/ue_bridge_load.c",
           "if (writer->overflow || end > writer->capacity)", "if (end > writer->capacity)",
           "load_reserve_past_the_capacity_sets_overflow_and_reserves_nothing"),
    Mutant("m2a-2", "port/ue_bridge/ue_bridge_load.c",
           "return (uint64_t)offset + (uint64_t)count * element_size <= capacity;", "return offset + count * element_size <= capacity;",
           "table_valid_checks_bounds_in_64_bits"),
    Mutant("m2a-2", "port/ue_bridge/ue_bridge_load.c",
           "if (index >= root->bsps.count)", "if (index > root->bsps.count)",
           "load_bsp_entry_indexes_the_counted_table"),
    Mutant("m2a-2", "port/ue_bridge/ue_bridge_ring.c",
           "if (used < used_offset + 4u || used > slot_size || used > out_capacity)", "if (used > out_capacity)",
           "slot_read_used_clamps_a_used_size_past_the_slot"),
    Mutant("m2a-2", "port/ue_bridge/ue_bridge_ring.c",
           "if (used < used_offset + 4u || used > slot_size || used > out_capacity)", "if (used < used_offset + 4u || used > out_capacity)",
           "slot_read_used_clamps_a_used_size_past_the_slot"),
    Mutant("m2a-2", "port/ue_bridge/ue_bridge_ring.c",
           "if (ueb_load_u32(&slot->sequence) != before)", "if (0)",
           "slot_read_used_detects_change_during_copy"),
    Mutant("m2a-2", "port/linux/src/ue_bridge_game.c",
           "if (section_mb < (long)UE_BRIDGE_MIN_SECTION_MB || section_mb > (long)(UE_BRIDGE_MAX_SECTION_SIZE >> 20))", "if (0)",
           "game_section_setting_out_of_range_uses_the_default_and_logs"),
    Mutant("m2a-3", "port/ue_bridge/ue_bridge_codec.c",
           "value = (float)(int32_t)(packed << 22);", "value = (float)(int32_t)(packed << 21);",
           "unpack_normal_extremes"),
    Mutant("m2a-3", "port/ue_bridge/ue_bridge_codec.c",
           "out->weight = (float)in->node_weight / 32767.0f;", "out->weight = (float)(uint8_t)in->node_weight / 255.0f;",
           "decode_model_vertex_as_the_gpu_reads_it"),
    Mutant("m2a-3", "port/ue_bridge/ue_bridge_codec.c",
           "out->node[0] = (uint8_t)(in->nodes[0] / 3u);", "out->node[0] = in->nodes[0];",
           "decode_model_vertex_as_the_gpu_reads_it"),
    Mutant("m2a-3", "port/ue_bridge/ue_bridge_codec.c",
           "if (index & 1u)", "if (0)",
           "strip_alternates_winding"),
    Mutant("m2a-3", "port/ue_bridge/ue_bridge_codec.c",
           "if (a == b || b == c || a == c)", "if (a == b)",
           "strip_drops_degenerate_triangles"),
    Mutant("m2a-3", "port/ue_bridge/ue_bridge_model.c",
           "if (remap[halo] < 0)", "if (1)",
           "model_export_keeps_each_used_geometry_once"),
    Mutant("m2a-3", "port/ue_bridge/ue_bridge_model.c",
           "if (source->parts[index].skip)", "if (0)",
           "model_export_decodes_parts_and_skips_stripped_ones"),
    Mutant("m2a-3", "port/ue_bridge/ue_bridge_model.c",
           "writer->used = start;", "(void)start;",
           "model_export_into_a_full_region_writes_nothing"),
    Mutant("m2a-4", "port/ue_bridge/ue_bridge_bsp.c",
           "if (scratch.owner[listed] == UNLISTED)", "if (1)",
           "bsp_export_counts_unclustered_and_duplicate_surfaces"),
    Mutant("m2a-4", "port/ue_bridge/ue_bridge_bsp.c",
           "if (listed < 0 || (uint32_t)listed >= source->surface_count)", "if (listed < 0)",
           "bsp_export_skips_surfaces_out_of_range"),
    Mutant("m2a-4", "port/ue_bridge/ue_bridge_bsp.c",
           "if (index == 0 || keys[index].shader != keys[index - 1u].shader)", "if (index == 0)",
           "bsp_export_groups_by_cluster_and_shader"),
    Mutant("m2a-4", "port/ue_bridge/ue_bridge_bsp.c",
           "material_stamp = (stamp + 1u) * BSP_STAMP_MATERIALS + (uint64_t)material + 1u;", "material_stamp = (stamp + 1u) * BSP_STAMP_MATERIALS;",
           "bsp_export_remaps_vertices_per_batch"),
    Mutant("m2a-4", "port/ue_bridge/ue_bridge_bsp.c",
           "if (source->surfaces[surface * 3u + index] >= source->materials[material].vertex_count)", "if (0)",
           "bsp_export_drops_a_surface_naming_a_missing_vertex"),
    Mutant("m2a-4", "port/ue_bridge/ue_bridge_bsp.c",
           "writer->used = start;", "(void)start;",
           "bsp_export_into_a_full_region_leaves_the_entry_unready"),
    Mutant("m2a-4", "port/ue_bridge/ue_bridge_bsp.c",
           "cluster_count = source->cluster_count < UE_BRIDGE_MAX_CLUSTERS ? source->cluster_count : UE_BRIDGE_MAX_CLUSTERS;", "cluster_count = source->cluster_count;",
           "bsp_export_does_not_store_a_cluster_the_index_type_cannot_hold"),
    Mutant("m2a-5", "port/linux/src/ue_bridge.c",
           "ueb_store_u32(&header->load_sequence, ueb_load_u32(&header->load_sequence) | 1u);", ";",
           "load_begin_marks_the_sequence_odd_and_clears_the_root"),
    Mutant("m2a-5", "port/linux/src/ue_bridge.c",
           "ue_bridge_load_writer_init(&bridge.load_writer, region, bridge.layout.load_region.size, 0);",
           "ue_bridge_load_writer_init(&bridge.load_writer, region, header->load_region.size, 0);",
           "load_begin_uses_the_game_layout_not_the_header"),
    Mutant("m2a-5", "port/linux/src/ue_bridge.c",
           "if (!header || !bridge.load_live || bridge.load_live_epoch != bridge.load_epoch)", "if (!header || !bridge.load_live)",
           "load_append_continues_after_the_export_of_this_epoch_only"),
    Mutant("m2a-5", "port/linux/src/ue_bridge.c",
           "ueb_store_u32(&header->export_epoch, bridge.load_epoch);", ";",
           "load_end_publishes_the_epoch_and_completeness"),
    Mutant("m2a-5", "port/linux/src/ue_bridge.c",
           "if (!complete)", "if (0)",
           "load_publish_bsp_sets_ready_and_can_clear_completeness"),
    Mutant("m2a-5", "port/linux/src/ue_bridge_game.c",
           "if (map && map[0])", "if (map)",
           "game_console_started_without_a_start_map_does_nothing"),
    Mutant("m2a-5", "port/linux/src/ue_bridge.c",
           "if (!bridge.section_view || !ue_bridge_table_valid(offset, count, sizeof(struct ue_bridge_bsp_entry), bridge.layout.load_region.size))", "if (!bridge.section_view)",
           "load_bsp_table_is_the_games_own_not_the_roots"),
    Mutant("m2a-5", "port/linux/src/ue_bridge.c",
           "if (!bridge.section_view || index >= bridge.bsp_count)", "if (!bridge.section_view)",
           "load_bsp_table_is_the_games_own_not_the_roots"),
    Mutant("m2a-4", "port/ue_bridge/ue_bridge_bsp.c",
           "[index * 3u + (corner == 0u ? 0u : 3u - corner)] = scratch->batch_index[vertex];", "[index * 3u + corner] = scratch->batch_index[vertex];",
           "bsp_export_remaps_vertices_per_batch"),
    Mutant("m2a-4", "port/ue_bridge/ue_bridge_bsp.c",
           "return left->first < right->first ? -1 : left->first > right->first;", "return right->first < left->first ? -1 : right->first > left->first;",
           "bsp_export_keeps_surface_order_within_a_shader"),
    Mutant("m2a-4", "port/ue_bridge/ue_bridge_bsp.c",
           "return left->position < right->position ? -1 : left->position > right->position;", "return 0;",
           "bsp_export_keeps_surface_order_within_a_shader"),
    Mutant("m2a-6", "port/ue_bridge/ue_bridge_tick.c",
           "if ((writer->flags & UE_BRIDGE_TICK_TRUNCATED) || (uint64_t)writer->used + size > writer->capacity)",
           "if ((uint64_t)writer->used + size > writer->capacity)",
           "tick_writer_marks_truncated_and_keeps_whole_records"),
    Mutant("m2a-6", "port/ue_bridge/ue_bridge_tick.c",
           "return continuing && memcmp(previous, latest, bytes) == 0;", "return memcmp(previous, latest, bytes) == 0;",
           "at_rest_needs_identical_bytes_and_a_continuing_record"),
    Mutant("m2a-6", "port/ue_bridge/ue_bridge_tick.c",
           "return continuing && memcmp(previous, latest, bytes) == 0;", "return continuing && memcmp(previous, latest, 4) == 0;",
           "at_rest_needs_identical_bytes_and_a_continuing_record"),
    Mutant("m2a-6", "port/ue_bridge/ue_bridge_tick.c",
           "return (uint32_t)sizeof(struct ue_bridge_object_record) + (((uint32_t)region_count + 3u) & ~3u) +",
           "return (uint32_t)sizeof(struct ue_bridge_object_record) + (uint32_t)region_count +",
           "record_size_pads_permutations_to_four"),
    Mutant("m2a-6", "port/linux/src/ue_bridge.c",
           "bridge.tick_slot->publish_qpc = bridge.os->qpc();", ";",
           "tick_begin_end_publishes_records_and_epochs"),
    Mutant("m2a-6", "port/linux/src/ue_bridge.c",
           "if (ueb_load_u32(&header->ue_ready) == bridge.load_epoch)", "if (0)",
           "hold_ends_when_ready"),
    Mutant("m2a-6", "port/linux/src/ue_bridge.c",
           "else if (*held_ms >= UE_BRIDGE_LOAD_HOLD_MS)", "else if (0)",
           "hold_ends_at_the_cap"),
    Mutant("m2a-6", "port/linux/src/ue_bridge.c",
           "else if (!ue_bridge_reader_present())", "else if (0)",
           "hold_ends_when_ue_detaches"),
    Mutant("m2a-6", "port/linux/src/ue_bridge.c",
           "if (ueb_load_u32(&header->ue_debugger_attached))", "if (0)",
           "hold_keeps_waiting_while_ue_is_in_a_debugger"),
    Mutant("m2a-6", "port/linux/src/ue_bridge.c",
           "if (!header || !ue_bridge_reader_present())", "if (!header)",
           "hold_needs_a_fresh_reader"),
    Mutant("m2a-6", "port/linux/src/ue_bridge_game.c",
           "if (started && window_index == 0)", "if (started)",
           "game_frame_end_publishes_window_zero_camera"),
    Mutant("m2a-6", "port/linux/src/ue_bridge_game.c",
           "ue_bridge_publish_frame_camera((uint64_t)frame, interpolation_fraction, (uint64_t)tick, frame_camera_valid ? &frame_camera : NULL);",
           "ue_bridge_publish_frame_camera((uint64_t)frame, interpolation_fraction, (uint64_t)tick, frame_camera_valid ? &frame_camera : &frame_camera);",
           "game_frame_end_publishes_window_zero_camera"),
    Mutant("m2a-6", "port/linux/src/ue_bridge_game.c",
           "if (!time_held && ue_bridge_world_hold_allowed() && ue_bridge_hold_begin())", "if (!time_held && ue_bridge_hold_begin())",
           "game_map_ready_in_a_network_game_does_not_hold"),
    Mutant("m2a-6", "port/linux/src/ue_bridge.c",
           "slot = (volatile struct ue_bridge_frame_slot *)trusted_begin_write(header, &header->frame_ring, &bridge.layout.frame_ring);",
           "slot = (volatile struct ue_bridge_frame_slot *)ue_bridge_ring_begin_write((volatile uint8_t *)header, &header->frame_ring);",
           "tick_and_frame_writes_use_the_trusted_layout_not_the_header"),
    Mutant("m2a-6", "port/linux/src/ue_bridge.c",
           "bridge.tick_slot = trusted_begin_write(header, &header->tick_ring, &bridge.layout.tick_ring);",
           "bridge.tick_slot = ue_bridge_ring_begin_write((volatile uint8_t *)header, &header->tick_ring);",
           "tick_and_frame_writes_use_the_trusted_layout_not_the_header"),
    Mutant("m2a-6", "port/linux/src/ue_bridge.c",
           "ue_bridge_tick_writer_begin(&bridge.tick_writer, (void *)(uintptr_t)bridge.tick_slot, bridge.layout.tick_ring.slot_size);",
           "ue_bridge_tick_writer_begin(&bridge.tick_writer, (void *)(uintptr_t)bridge.tick_slot, header->tick_ring.slot_size);",
           "tick_and_frame_writes_use_the_trusted_layout_not_the_header"),
    Mutant("m2a-6", "port/linux/src/ue_bridge.c",
           "else if (*held_ms >= UE_BRIDGE_LOAD_HOLD_MS)", "else if (*held_ms > UE_BRIDGE_LOAD_HOLD_MS)",
           "hold_ends_exactly_at_the_cap"),
    Mutant("m2a-6", "port/linux/src/ue_bridge.c",
           "if (__atomic_load_n(&bridge.peer_exited, __ATOMIC_SEQ_CST))", "if (0)",
           "hold_ends_at_once_when_the_renderer_process_exits"),
    Mutant('fw-1', 'port/ue_bridge/ue_bridge_load.c',
           'if (count == UINT64_MAX)',
           'if (0)',
           'padded_array_bytes_refuses_what_wraps_size_t'),
    Mutant('fw-1', 'port/ue_bridge/ue_bridge_load.c',
           'if (element_size && elements > (uint64_t)SIZE_MAX / element_size)',
           'if (0)',
           'padded_array_bytes_refuses_what_wraps_size_t'),
    Mutant('fw-1', 'port/ue_bridge/ue_bridge_load.c',
           'elements = count + 1u;',
           'elements = count;',
           'padded_array_bytes_counts_one_spare_element'),
    Mutant('fw-1', 'port/ue_bridge/ue_bridge_bsp.c',
           'return sum > limit ? limit : (uint32_t)sum;',
           'return (uint32_t)sum;',
           'bsp_capacity_add_sums_and_saturates_at_the_limit'),
    Mutant('fw-1', 'port/ue_bridge/ue_bridge_bsp.c',
           'uint64_t sum = (uint64_t)capacity + count;',
           'uint64_t sum = (uint32_t)(capacity + count);',
           'bsp_capacity_add_sums_and_saturates_at_the_limit'),
    Mutant('fw-2', 'port/linux/src/ue_bridge.c',
           'ue_bridge_tick_writer_end(&bridge.tick_writer, bridge.load_epoch, bridge.state_epoch, active_bsp);',
           'ue_bridge_tick_writer_end(&bridge.tick_writer, header->load_epoch, header->state_epoch, active_bsp);',
           'epochs_are_the_games_own_not_read_back_from_the_header'),
    Mutant('fw-2', 'port/linux/src/ue_bridge.c',
           'ueb_store_u32(&header->load_epoch, ++bridge.load_epoch);',
           'ueb_store_u32(&header->load_epoch, header->load_epoch + 1u);',
           'epochs_are_the_games_own_not_read_back_from_the_header'),
    Mutant('fw-2', 'port/linux/src/ue_bridge.c',
           'ueb_store_u32(&header->state_epoch, ++bridge.state_epoch);',
           'ueb_store_u32(&header->state_epoch, header->state_epoch + 1u);',
           'epochs_are_the_games_own_not_read_back_from_the_header'),
    Mutant('fw-2', 'port/linux/src/ue_bridge.c',
           'ueb_store_u32(&header->export_epoch, bridge.load_epoch);',
           'ueb_store_u32(&header->export_epoch, header->load_epoch);',
           'load_end_and_append_follow_the_games_epoch_not_the_headers'),
    Mutant('fw-2', 'port/linux/src/ue_bridge.c',
           'bridge.load_live_epoch != bridge.load_epoch)',
           'bridge.load_live_epoch != header->load_epoch)',
           'load_end_and_append_follow_the_games_epoch_not_the_headers'),
    Mutant('fw-2', 'port/linux/src/ue_bridge.c',
           'if (ueb_load_u32(&header->ue_ready) == bridge.load_epoch)',
           'if (ueb_load_u32(&header->ue_ready) == header->load_epoch)',
           'hold_ready_means_the_games_epoch_not_the_headers'),
    Mutant('fw-d2', 'port/linux/src/ue_bridge.c',
           'bridge.load_sequence |= 1u;',
           'bridge.load_sequence = ueb_load_u32(&header->load_sequence) | 1u;',
           'load_sequence_is_the_games_own_not_read_back_from_the_header'),
    Mutant('fw-d2', 'port/linux/src/ue_bridge.c',
           'bridge.load_sequence = (bridge.load_sequence | 1u) + 1u;',
           'bridge.load_sequence = (ueb_load_u32(&header->load_sequence) | 1u) + 1u;',
           'load_sequence_is_the_games_own_not_read_back_from_the_header'),
    Mutant('fw-3', 'port/ue_bridge/ue_bridge_load.c',
           'return definition_count <= UE_BRIDGE_MAX_DEFINITIONS && model_count <= UE_BRIDGE_MAX_MODELS;',
           'return definition_count < UE_BRIDGE_MAX_DEFINITIONS && model_count <= UE_BRIDGE_MAX_MODELS;',
           'index_counts_fit_holds_the_sixteen_bit_fields'),
    Mutant('fw-3', 'port/ue_bridge/ue_bridge_load.c',
           'return definition_count <= UE_BRIDGE_MAX_DEFINITIONS && model_count <= UE_BRIDGE_MAX_MODELS;',
           'return definition_count <= UE_BRIDGE_MAX_DEFINITIONS && model_count < UE_BRIDGE_MAX_MODELS;',
           'index_counts_fit_holds_the_sixteen_bit_fields'),
    Mutant('fw-3', 'port/ue_bridge/ue_bridge_load.c',
           'return definition_count <= UE_BRIDGE_MAX_DEFINITIONS && model_count <= UE_BRIDGE_MAX_MODELS;',
           'return definition_count <= UE_BRIDGE_MAX_DEFINITIONS || model_count <= UE_BRIDGE_MAX_MODELS;',
           'index_counts_fit_holds_the_sixteen_bit_fields'),
    Mutant('fw-4', 'port/ue_bridge/ue_bridge_format.h',
           '#define UE_BRIDGE_VERSION 4u',
           '#define UE_BRIDGE_VERSION 3u',
           'format_version_is_four'),
    Mutant('fw-5', 'port/linux/src/ue_bridge.c',
           'ueb_store_u32(&header->game_truncated_ticks, ++bridge.truncated_ticks);',
           'ueb_store_u32(&header->game_truncated_ticks, header->game_truncated_ticks + 1u);',
           'truncated_ticks_are_counted_and_logged_once_per_epoch'),
    Mutant('fw-5', 'port/linux/src/ue_bridge.c',
           'if (!bridge.truncation_logged || bridge.truncation_logged_epoch != bridge.load_epoch)',
           'if (1)',
           'truncated_ticks_are_counted_and_logged_once_per_epoch'),
    Mutant('fw-5', 'port/linux/src/ue_bridge.c',
           'if (!bridge.truncation_logged || bridge.truncation_logged_epoch != bridge.load_epoch)',
           'if (!bridge.truncation_logged)',
           'truncated_ticks_are_counted_and_logged_once_per_epoch'),
    Mutant('fw-5', 'port/linux/src/ue_bridge.c',
           'if (bridge.tick_writer.flags & UE_BRIDGE_TICK_TRUNCATED)',
           'if (1)',
           'truncated_ticks_are_counted_and_logged_once_per_epoch'),
    Mutant('fw-6', 'port/linux/src/ue_bridge_game.c',
           'ue_bridge_load_end(complete);',
           '(void)complete;',
           'game_map_ready_publishes_the_first_tick_before_the_export_ends'),
    Mutant('fw-6', 'port/linux/src/ue_bridge_game.c',
           'complete = ue_bridge_world_export_map();',
           'complete = ue_bridge_world_export_map(); ue_bridge_load_end(complete);',
           'game_map_ready_publishes_the_first_tick_before_the_export_ends'),
    Mutant('fw-6', 'port/linux/src/ue_bridge_game.c',
           'ue_bridge_world_publish_tick((uint64_t)last_tick);',
           '(void)last_tick;',
           'game_map_ready_publishes_the_first_tick_before_the_export_ends'),
    Mutant('fw-8', 'port/linux/src/ue_bridge_game.c',
           'ue_bridge_load_discard();',
           ';',
           'game_loading_closes_the_previous_export_to_appends'),
    Mutant('fw-8', 'port/linux/src/ue_bridge.c',
           'bridge.load_live = 1;',
           ';',
           'load_discard_closes_appends_until_the_next_export_ends'),
    Mutant('fw-9', 'port/linux/src/ue_bridge.c',
           'return bridge.section_view != 0 && ue_bridge_nodes_at_rest(previous, latest, bytes, continuing);',
           'return ue_bridge_nodes_at_rest(previous, latest, bytes, continuing);',
           'at_rest_compare_runs_only_while_the_bridge_is_active'),
]


PYTEST_ENV = {**os.environ,
              # a plugin installed in the user's environment (web3's) crashes pytest on start
              "PYTEST_DISABLE_PLUGIN_AUTOLOAD": "1"}

KILLED, SURVIVED, INVALID = "killed", "survived", "invalid"
TIMED_OUT = -1


def run_pytest(test: str) -> subprocess.CompletedProcess:
    try:
        return subprocess.run([sys.executable, "-m", "pytest", "tools/test_ue_bridge.py", "-q", "-x", "-k", test],
                              cwd=ue_bridge_tests.ROOT, capture_output=True, text=True, env=PYTEST_ENV, timeout=300)
    except subprocess.TimeoutExpired as expired:
        # neither a pass nor a failure: reported as an invalid run
        return subprocess.CompletedProcess(expired.cmd, TIMED_OUT, "", "timed out")


def verify_clean_tree(mutants: list[Mutant]) -> None:
    """every pytest-named test must pass on the unmutated tree, or a failure under a mutant proves nothing"""
    for test in sorted({m.killed_by[len("pytest:"):] for m in mutants if m.killed_by.startswith("pytest:")}):
        result = run_pytest(test)
        if result.returncode != 0 or "passed" not in result.stdout:
            if result.returncode == TIMED_OUT:
                rc = "timed out"
            else:
                rc = f"exit {result.returncode}"
            raise SystemExit(f"{test} does not pass on the clean tree ({rc}); not mutating:\n{result.stdout[-2000:]}")


C_TEST_TIMEOUT_S = 120


def judge(mutant: Mutant) -> tuple[str, str]:
    """the best verdict of the mutant's runs: killed if any run kills it, else invalid if any run
    was invalid, else survived"""
    verdicts = [judge_once(mutant) for _ in range(mutant.runs)]
    killed = [v for v in verdicts if v[0] == KILLED]
    invalid = [v for v in verdicts if v[0] == INVALID]
    if killed:
        verdict, reason = killed[0]
        if invalid:
            reasons = ", ".join(v[1] for v in invalid)
            return verdict, f"also {len(invalid)} of {len(verdicts)} runs invalid: {reasons}"
        return verdict, reason
    if invalid:
        return invalid[0]
    return verdicts[0]


def judge_once(mutant: Mutant) -> tuple[str, str]:
    """(verdict, reason). Killed only by a real test failure: exit 1 with 'failed' in the output. A
    collection or setup error, 'no tests ran' (exit 5), a build failure, a crash and a timeout say
    nothing about the test, so they are invalid."""
    if mutant.killed_by.startswith("pytest:"):
        result = run_pytest(mutant.killed_by[len("pytest:"):])
        if result.returncode == 1 and " failed" in result.stdout:
            return KILLED, ""
        if result.returncode == TIMED_OUT:
            return INVALID, "timed out"
        return (SURVIVED, "") if result.returncode == 0 else (INVALID, f"pytest exit {result.returncode}")
    try:
        exe = ue_bridge_tests.build()
    except subprocess.CalledProcessError:
        return INVALID, "does not compile"
    try:
        result = subprocess.run([str(exe), mutant.killed_by], capture_output=True, timeout=C_TEST_TIMEOUT_S)
    except subprocess.TimeoutExpired:
        return INVALID, f"test runner timed out after {C_TEST_TIMEOUT_S}s"
    if result.returncode == 1:
        return KILLED, ""
    return (SURVIVED, "") if result.returncode == 0 else (INVALID, f"test runner exit {result.returncode}")


def outcome(mutant: Mutant) -> tuple[str, str]:
    path = ue_bridge_tests.ROOT / mutant.path
    # bytes, not text: text mode would rewrite line endings, so restoring would not be byte for byte
    data = path.read_bytes()
    original = mutant.original.encode("utf-8")
    if data.count(original) != 1:
        raise RuntimeError(f"{mutant.path}: {mutant.original!r} must occur exactly once")
    try:
        path.write_bytes(data.replace(original, mutant.mutated.encode("utf-8")))
        return judge(mutant)
    finally:
        path.write_bytes(data)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("task", nargs="?")
    parser.add_argument("--path", action="append", default=[])
    args = parser.parse_args()
    paths = {p.replace("\\", "/") for p in args.path}
    selected = [m for m in MUTANTS
                if (args.task is None or m.task == args.task) and (not paths or m.path in paths)]
    unmatched = sorted(p for p in paths if not any(m.path == p and (args.task is None or m.task == args.task) for m in MUTANTS))
    if unmatched:
        raise SystemExit(f"no mutant matches --path {', '.join(unmatched)}")
    if not selected:
        raise SystemExit("no mutant matches the task and path filters")
    verify_clean_tree(selected)
    survivors = []
    invalid = []
    for mutant in selected:
        result, reason = outcome(mutant)
        if result == SURVIVED:
            survivors.append(mutant)
        elif result == INVALID:
            invalid.append((mutant, reason))
    for m in survivors:
        print(f"SURVIVED task {m.task}: {m.path}: {m.original!r} -> {m.mutated!r} ({m.killed_by} still passes)")
    for m, reason in invalid:
        print(f"INVALID task {m.task}: {m.path}: {m.original!r} -> {m.mutated!r} ({m.killed_by}: {reason})")
    print(f"{len(survivors)} survivor(s), {len(invalid)} invalid run(s)")
    return 1 if survivors or invalid else 0


if __name__ == "__main__":
    sys.exit(main())
